### ISSUE TITLE
ImportError: DLL load failed while importing renderutils_plugin

### ISSUE THREAD

**Issue by zouxiaohang** [NVlabs/nvdiffmodeling#32]
![image](https://github.com/NVlabs/nvdiffmodeling/assets/3312797/2a21630d-5274-4cac-af28-38a6c926696c)
here is the folder of renderutils_plugin
![image](https://github.com/NVlabs/nvdiffmodeling/assets/3312797/3462648d-39f4-45ca-be1b-d1930b07430a)

**Comment by zouxiaohang** [comment]
It seems that the dll file is missing. This dll file should be compiled and generated, but I did not find this dll after following the tutorial.

**Comment by JHnvidia** [comment]
Hi,

This is probably some versioning issue between Visual Studio, CUDA SDK & Pytorch. There's not supposed to be a dll file in the ninja cache directory. AFAIK the DLL file is created somehow by pytorch. Below is a screenshot of my cache folder (note, I'm running pytorch 2 with cuda 11.7, and python 3.9). Since your pytorch container seems to be running cuda 11.8 make sure you have the same version of the SDK installed (and set as CUDA_PATH).

![bild](https://github.com/NVlabs/nvdiffmodeling/assets/40264125/a7c1e143-286f-4107-a11d-d54e28795f40)

There's a thread in the stylegan repo with a similar issue, which may give some additional information:
https://github.com/NVlabs/stylegan3/issues/88

**Comment by zouxiaohang** [comment]
@JHnvidia I changed the cuda version to 11.8 and it was solved, thank you
